In [604]:
import mycount

In [613]:
formatted_harry_txt = mycount.format_harry_potter('harry_potter_stein_weisen.txt')
kw = mycount.read_known_word_list('duolingo_words_learned.txt')
b = mycount.Book(formatted_harry_txt, kw)
df=b.word_data

Total number of words:  80428
Number of unique words:  9477

Print all words that appear more than five times in book and weren't learned on duolingo, sorted by page on which they first appear:

In [611]:
chunk = df[(df['count']>5) & (df['learned']==False)].sort_values(['page'])
chunk

                count learned  page
4                  11   False     5
deren               8   False     5
wäre               53   False     5
groß               21   False     5
dursley            54   False     5
jahren             15   False     5
merkwürdige        10   False     5
großen             54   False     5
könnte             38   False     5
wollten            16   False     5
würden             30   False     5
namens             10   False     5
bloß               10   False     5
mr                 76   False     5
mrs                44   False     5
hals               20   False     5
nummer              9   False     5
könnten            16   False     5
gekommen           20   False     5
sorge               7   False     5
besaß               6   False     5
gesehen            66   False     5
sagen              92   False     5
idee                6   False     5
unsinn              9   False     5
potter            100   False     5
in               1002   False     5
sich              851   False     5
hatte             485   False     5
ligusterweg        12   False     5
...               ...     ...   ...
keule               6   False   192
trolls              7   False   193
fünfzig             9   False   195
sinken              6   False   195
hängen              6   False   196
schiedsrichter      6   False   199
stehlen             9   False   201
rängen              6   False   202
flint              14   False   203
fernglas            6   False   205
fluffy             26   False   210
nerhegeb            7   False   212
abteilung           7   False   216
figuren             9   False   217
zettel             11   False   218
flöte               6   False   218
weiße               7   False   222
tamumhang           8   False   224
weisen             14   False   239
a                   8   False   242
lichtung            6   False   246
norbert            26   False   249
prüfungen           7   False   249
stachelbuckel       6   False   249
ronan              20   False   275
zentaur             6   False   275
zentauren           6   False   275
bane               16   False   276
firenze            18   False   280
gruft               8   False   303

[970 rows x 3 columns]